### ISSUE TITLE
U256 token balances

### ISSUE THREAD

**Issue by birchmd** [MovedNetwork/op-move#56]
The Ethereum standard for token balances (ETH, ERC20) is to use the U256 data type. In the Aptos Move framework though it is u64. We probably need to write our own token standard in Move that uses U256 balances.

Code reference:
https://github.com/MovedNetwork/op-move/blob/79df431c0deb8cfe59303d13adff50cbff10ec62/moved/src/move_execution.rs#L69

**Comment by bulenttastan** [comment]
Working on keeping the u256 balance as 4 of u64 limbs.

**Comment by birchmd** [comment]
Why not use Move's built-in u256 type?

**Comment by bulenttastan** [comment]
> Why not use Move's built-in u256 type?

Externally it will be exposed as `u256` like you mentioned, but internally I'm thinking of keeping 4 fungible tokens. Otherwise, the `amount` type in fungible token is hardcoded to u64 and changing it touches a lot of the framework code we need to copy and maintain.

**Comment by birchmd** [comment]
Interesting idea! That might work out to be less code than forking the fungible asset itself. I would worry about handling the metadata and asset stores correctly for the internal tokens, but maybe it won't be that much work. Certainly worth a try anyway.
